
champions = ['Aatrox',
             'Ahri',
             'Akali',
             'Alistar',
             'Amumu',
             'Anivia',
             'Annie',
             'Aphelios',
             'Ashe',
             'Aurelion Sol',
             'Azir',
             'Bard',
             'Blitzcrank',
             'Brand',
             'Braum',
             'Caitlyn',
             'Camille',
             'Cassiopeia',
             'Cho\'\'Gath', # Double single quote is the escape char in SQL... we'll see how it handles it
             'Corki',
             'Darius',
             'Diana',
             'Dr. Mundo',
             'Draven',
             'Ekko',
             'Elise',
             'Evelynn',
             'Ezreal',
             'Fiddlesticks',
             'Fiora',
             'Fizz',
             'Galio',
             'Gangplank',
             'Garen',
             'Gnar',
             'Gragas',
             'Graves',
             'Hecarim',
             'Heimerdinger',
             'Illaoi',
             'Irelia',
             'Ivern',
             'Janna',
             'Jarvan IV',
             'Jax',
             'Jayce',
             'Jhin',
             'Jinx',
             'Kai\'\'Sa',  # Again, we'll see how SQL handles the atempt at the escape char
             'Kalista',
             'Karma',
             'Karthus',
             'Kassadin',
             'Katarina',
             'Kayle',
             'Kayn',
             'Kennen',
             'Kha\'\'zix',  # Aother attempt
             'Kindred',
             'Kled',
             'Kog\'\'maw', # Another one
             'LeBlanc',
             'Lee Sin',
             'Leona',
             'Lissandra',
             'Lucian',
             'Lulu',
             'Lux',
             'Malphite',
             'Malzahar',
             'Maokai',
             'Master Yi',
             'Miss Fortune',
             'Mordekaiser',
             'Morgana',
             'Nami',
             'Nasus',
             'Nautilus',
             'Neeko',
             'Nidalee',
             'Nocturne',
             'Nunu & Willump',
             'Olaf',
             'Orianna',
             'Ornn',
             'Pantheon',
             'Poppy',
             'Pyke',
             'Qiyana',
             'Quinn',
             'Rakan',
             'Rammus',
             'Rek\'\'Sai', # https://www.youtube.com/watch?v=09XkgyfV0c4
             'Renekton',
             'Rengar',
             'Riven',
             'Rumble',
             'Ryze',
             'Sejuani',
             'Senna',
             'Sett',
             'Shaco',
             'Shen',
             'Shyvana',
             'Singed',
             'Sion',
             'Sivir',
             'Skarner',
             'Sona',
             'Soraka',
             'Swain',
             'Sylas',
             'Syndra',
             'Tahm Kench',
             'Taliyah',
             'Talon',
             'Taric',
             'Teemo',
             'Thresh',
             'Tristana',
             'Trundle',
             'Tryndamere',
             'Twisted Fate',
             'Twitch',
             'Udyr',
             'Urgot',
             'Varus',
             'Vayne',
             'Veigar',
             'Vel\'\'Koz',# https://i.kym-cdn.com/news_feeds/icons/mobile/000/019/699/7f7.jpg
             'Vi',
             'Viktor',
             'Vladimir',
             'Volibear',
             'Warwick',
             'Wukong',
             'Xayah',
             'Xerath',
             'Xin Zhao',
             'Yasuo',
             'Yorick',
             'Yuumi',
             'Zac',
             'Zed',
             'Ziggs',
             'Zilean',
             'Zoe',
             'Zyra'
             ]

with open('Champions.sql', 'w') as f: 
    for i in range(1,len(champions)+1):
        f.write("INSERT INTO Champions (ChampionID, ChampionName) VALUES ({},\'{}\');\n".format(i, champions[i-1]))
    
